### ISSUE TITLE
AttributeError: 'TemporalRoIHeads' object has no attribute 'tracking_predictor'

### ISSUE THREAD

**Issue by young-yangb** [HumaticsLAB/SEAM-Match-RCNN#1]
Hi, Thank you for your code!
when I run train_movingfashion.py, it runs to a AttributeError: 
'TemporalRoIHeads' object has no attribute 'tracking_predictor' at video_matchrcnn.py (line 327, in load_saved_matchrcnn)
How can I fix it?

**Comment by joppichristian** [comment]
Hello,
you can remove that part of the code (load tracking predictor weights, two lines). I just proceeded to remove it in a new commit of the code.
Thanks for reporting this issue!

**Comment by young-yangb** [comment]
Hi, I remove that part of code and encounter another KeyError:
'Caught KeyError in DataLoader worker process 0.'  at datasets/MFDataset.py", line 69, in __getitem__ 
      if str(index2) in self.product_list[i]['tracklets'][0]:
KeyError: 'tracklets'

**Comment by young-yangb** [comment]
> Hello, you can remove that part of the code (load tracking predictor weights, two lines). I just proceeded to remove it in a new commit of the code. Thanks for reporting this issue!

It seems that there are no trackets in the self.product_list, and I can't find the code to generate tracklets. How can I solve this problem?

**Comment by joppichristian** [comment]
During training or evaluation?

**Comment by young-yangb** [comment]
> During training or evaluation?

training, train_movingfashion.py

**Comment by joppichristian** [comment]
Ok, I fixed some missed bugs. I suggest cloning the code again or checking the modified files.

Thanks!
