### ISSUE TITLE
The download link movingFashion not working :(

### ISSUE THREAD

**Issue by thuc248997** [HumaticsLAB/SEAM-Match-RCNN#7]

**Comment by WillowKaze** [comment]
Please give a new valid link of this dataset and We will appreciate it.

**Comment by dmangla3** [comment]
Same issue

**Comment by joppichristian** [comment]
Hi everyone!
We are replacing our data storage, and then all the links should be replaced!
We are uploading the dataset on the new storage. As soon as the uploading is finished, I can share the new link with you!

**Comment by joppichristian** [comment]
Here the new [dataset](https://bit.ly/3OxetTl)
